### ISSUE TITLE
psl.hrsn.dev redirections

### ISSUE THREAD

**Issue by groundcat** [wdhdev/psl-formatted#1]
Hi @wdhdev, it seems the site https://psl.hrsn.dev/ is showing an `ERR_TOO_MANY_REDIRECTS` error. Maybe it could be an issue with the Cloudflare edge SSL configuration (full vs. flexible)?

![image](https://github.com/user-attachments/assets/200d746b-6f82-4994-b084-d66508eb7005)

**Comment by wdhdev** [comment]
Thanks for reporting, it was due to Cloudflare's SSL mode being set to Flexible (I forgot to update it when I moved the domain to a dedicated zone on Cloudflare). It has been changed to Full, and it should work now.
